db.tasks.insertMany([
    {projectName: "FaceID System", description: "Face recognition", workers: ["Shtepa", "Victor"], manager: "Vanya Face", startDate: "2020-10-10", endDate: "2020-11-22"},
    {projectName: "FaceID System", description: "Wrinkles recognition", workers: ["Vadim", "Pavel", "Vlados"], manager: "Vanya Face", startDate: "2020-11-10", endDate: "2020-11-20"},
    {projectName: "FaceID System", description: "Nose recognition", workers: "Vlados", manager: "Vanya Face", startDate: "2020-11-10", endDate: "2020-12-21"},
    {projectName: "Meme Generator", description: "Preparation of a neural neural network for trollface recognition", workers: ["Rick Roll", "Ricardo"], manager: "Vadim Palich", startDate: "2007-01-01", endDate: "2007-01-02"},
    {projectName: "Meme Generator", description: "Rickroll meme", workers: ["Rick Roll", "Maks"], manager: "Vadim Palich", startDate: "2007-04-20", endDate: "2007-04-20"},
    {projectName: "Meme Generator", description: "Successful Black Man", workers: "Black Man", manager: "Vadim Palich", startDate: "2010-01-01", endDate: "2010-01-02"},
    {projectName: "Meme Generator", description: "Omae Wa Mou Shindeiru", workers: ["Kenshiro", "Tencuro Hara"], manager: "Vadim Palich", startDate: "2011-04-20", endDate: "2011-05-02"},
    {projectName: "Meme Generator", description: "Pink Guy", workers: "Joji", manager: "Vadim Palich", startDate: "2012-04-21", endDate: "2012-05-13"},
    {projectName: "Meme Generator", description: "Ricardo", workers: "Ricardo Milos", manager: "Vadim Palich", startDate: "2013-04-11", endDate: "2014-05-15"},
    {projectName: "Meme Generator", description: "Giga Chad", workers: ["Felix Kchelberg", "Chad"], manager: "Vadim Palich", startDate: "2020-06-12", endDate: "2020-07-13"},
    {projectName: "Body Verification", description: "Legs verification", workers: ["Belle Dolphine", "Johny Sins"], manager: "Elsa Jean", startDate: "2020-04-21", endDate: "2020-07-23"},
    {projectName: "Body Verification", description: "Hips verification", workers: ["Mia Khalifa", "Lexi Belle"], manager: "Elsa Jean", startDate: "2020-03-21", endDate: "2020-05-23"},
    {projectName: "Body Verification", description: "Navel verification", workers: ["Jesse Jane", "August Ames"], manager: "Elsa Jean", startDate: "2020-07-21", endDate: "2020-08-23"},
    {projectName: "Body Verification", description: "Chest verification", workers: ["Pinky", "Lisa Ann"], manager: "Elsa Jean", startDate: "2020-09-21", endDate: "2020-10-23"},
    {projectName: "Body Verification", description: "Teeth verification", workers: ["Dani Daniels", "Kendra Lust"], manager: "Elsa Jean", startDate: "2020-11-21", endDate: "2020-12-23"},
    {projectName: "Multiplication Table", description: "Fundamental Math", manager: "Pythagoras"},
    {projectName: "Flying Sofa", description: "Plugging Pratt & Whitney F119 engine in sofa", workers: ["Dill", "Bill"], manager: "Elon Tusk", startDate: "2021-01-03", endDate: "2021-01-04"},
    {projectName: "Flying Sofa", description: "Funeral collections", workers: ["Fill", "Pill"], manager: "Elon Tusk", startDate: "2021-01-04", endDate: "2021-01-05"},
])